#!/bin/sh

if [ "$1" = "" ]; then echo "Usage: $0 <main.click>"; exit 1; fi

if [ "$(basename $1)" = "$1" ]  # config file is in script dir
then
  SCRIPTDIR=$(dirname $0)/
else
  SCRIPTDIR=$(dirname $1)/
fi

exec sed 's/^\s*include/include/' $SCRIPTDIR$(basename $1) | awk -F '[ ();]+' "{ if (\$1 == \"include\") system(\"$0 $SCRIPTDIR\"\$2); else print \$0 }"
